version: 2.1

jobs:
  build:
    docker:
     - image: cimg/node:16.13.2
    steps:
     - checkout
     - run: npm update
     - run:
          name: Start Localhost Server
          command: |
            npm run dev 3000 &
            sleep 10 # Wait for the server to start
     - run: npm test
