version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:16.13.2
    working_directory: /.
    steps:
      - checkout
      - run: npm update
      - run:
          name: Start Localhost Server
          background: true
          command: |
            npm run dev 3000
            sleep 20 # Wait for the server to start
      - run:
          name: Run API Tests
          command: |
            npm run apitest
          when: always
      - run:
          name: Run UI Tests
          command: |
            npm run uitest
          when: always
      - run:
          name: Stop Localhost Server
          command: |
            # Stop the server gracefully
            pkill -f "npm run dev 3000"
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
