version: 2.1

jobs:
  build:
    docker:
     - image: cimg/node:16.13.2
    steps:
     - checkout
     - run: npm update
     - run: 
       command: npm run dev 3000
       background: true
     - run: npm test
