yaml
version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:16.13.2
    steps:
      - checkout
      - run: npm update
      - run:
          name: Start Localhost Server
          background: true
          command: |
            npm run dev 3000
            sleep 20 # Wait for the server to start
      - run:
          name: Run Tests
          command: |
            cd Automation-Task/nightwatch/examples/ui-tests
            npm install
            npm test
      - run:
          name: Stop Localhost Server
          command: |
            # Stop the server gracefully
            pkill -f "npm run dev 3000"
